trigger:
  - main  # or your branch name

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'clarawebapp'

steps:
- task: Docker@2
  displayName: 'Build Docker image'
  inputs:
    command: build
    repository: $(imageName)
    Dockerfile: '**/Dockerfile'
    tags: |
      latest

- task: Docker@2
  displayName: 'Push image to ACR'
  inputs:
    command: push
    repository: $(imageName)
    tags: |
      latest
    containerRegistry: 'YOUR_ACR_SERVICE_CONNECTION_NAME'

- task: Kubernetes@1
  displayName: 'Deploy to AKS'
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscription: 'YOUR_AZURE_SUBSCRIPTION_NAME'
    azureResourceGroup: 'YOUR_RESOURCE_GROUP'
    kubernetesCluster: 'YOUR_CLUSTER_NAME'
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: 'k8s/deployment.yaml'
